# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Pod-LaTeX-TPR
version:      1.07
version_from: lib/TPR.pm
installdirs:  site
requires:
    Pod::LaTeX:                    0.54
    Test::Manifest:                0.9
    Test::More:                    0
    Test::Pod:                     0.90
    Test::Prereq:                  0.18

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
